name: TypeScript Action
author: Austen Stone
description: A TypeScript Action
branding:
  icon: "list"
  color: "blue"

inputs:
  github-token:
    description: The GitHub token used to create an authenticated client
    default: ${{ github.token }}
    required: false
  owner:
    description: The owner of the repository
    default: ${{ github.repository_owner }}
    required: false
  repo:
    description: The name of the repository
    default: ${{ github.event.repository.name }}
    required: false

outputs:
  languages:
    description: The languages of the repository as a JSON array

runs:
  using: "node16"
  main: "dist/index.js"
