name: TypeScript Action Workflow
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  run:
    name: Run Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        id: list-repo-langs
      - run: echo ${{ steps.list-repo-langs.outputs.languages }}
      - run: echo ${{ toJSON(steps.list-repo-langs.outputs.languages) }}
      - run: echo ${{ fromJSON(steps.list-repo-langs.outputs.languages) }}