name: Print Languages
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        id: list-languages
      - run: echo ${{ join(fromJSON(steps.list-languages.outputs.languages), ', ') }}